
on:
  push:
    branches:
      - master      
jobs:
  build:
    runs-on: ubuntu-latest 
    steps:
      - uses: actions/checkout@v3
      
      - name: " login to dockerhub"
        run: docker login --username ${{ secrets.DOCKERMAIL1 }} --password ${{ secrets.DOCKERPASSWORD1 }}
      - name: " building docker "
        run: docker build -t ${{secrets.DOCKERMAIL1}}/javat:dev .
      - name: " pushing to docker hub "
        run: docker push ${{secrets.DOCKERMAIL1}}/javat:dev
